#!/bin/bash

# Exit on failure
set -e

# ARGS

OPTION=${1}

# CONSTANTS

SCRIPT_FILE="/srv/lib/write-user-config"
HOSTNAME="vm999"

# VALIDATE

if [[ "${OPTION}" == "" ]];
then
  OPTION="--execute"
fi

# START

/srv/tests/lib/run-test "${OPTION}" "${SCRIPT_FILE}" "${HOSTNAME}"
