#!/bin/bash

# ARGS

OPTION=${1}
SCRIPT_FILE=${2}
ARGUMENTS="${@:3}"

# CONSTANTS

ACTUAL_FILE="/srv/tests/actual${SCRIPT_FILE}"
EXPECTED_FILE="/srv/tests/expected${SCRIPT_FILE}"

# VALIDATE

if [[ "${OPTION}" != "--execute" && "${OPTION}" != "--update" ]];
then
  echo "FAILED: Invalid OPTION: ${OPTION}"
  exit 1
fi

if [[ ! -f ${ACTUAL_FILE} ]];
then
  mkdir -p $(dirname "${ACTUAL_FILE}")
  touch ${ACTUAL_FILE}
fi

if [[ ! -f ${EXPECTED_FILE} ]];
then
  mkdir -p $(dirname "${EXPECTED_FILE}")
  touch ${EXPECTED_FILE}
fi

# START

if ! ${SCRIPT_FILE} ${ACTUAL_FILE} ${ARGUMENTS};
then
  echo "##### TEST FAILED: The script returned an error code."
  exit 1
fi

if cmp --silent -- ${EXPECTED_FILE} ${ACTUAL_FILE};
then
  echo "##### TEST PASSED"
else
  echo "##### TEST FAILED: Actual and expected did not match."
  colordiff --side-by-side ${EXPECTED_FILE} ${ACTUAL_FILE}
fi


if [[ "${OPTION}" == "--update" ]];
then
  echo "##### Updating expected file"
  cp ${ACTUAL_FILE} ${EXPECTED_FILE}
fi
