#!/bin/bash

# ARGS

SCRIPT_FILE=${1}
ARGUMENTS="${@:2}"

# CONSTANTS

ACTUAL_FILE="/srv/tests/actual${SCRIPT_FILE}"
EXPECTED_FILE="/srv/tests/expected${SCRIPT_FILE}"

# VALIDATE

if [[ ! -f ${ACTUAL_FILE} ]];
then
  mkdir -p $(dirname "${ACTUAL_FILE}")
  touch ${ACTUAL_FILE}
fi

if [[ ! -f ${EXPECTED_FILE} ]];
then
  mkdir -p $(dirname "${EXPECTED_FILE}")
  touch ${EXPECTED_FILE}
fi

# START

DISCARD=$(${SCRIPT_FILE} ${ACTUAL_FILE} ${ARGUMENTS})

if cmp --silent -- ${EXPECTED_FILE} ${ACTUAL_FILE};
then
  echo "##### TEST PASSED"
else
  echo "##### TEST FAILED: Actual and expected did not match."
  diff --side-by-side ${EXPECTED_FILE} ${ACTUAL_FILE}
fi
