#!/bin/bash
set -euo pipefail

SRC_ARRAY=( "$@" )
SRC_ARRAY_COUNT=${#SRC_ARRAY[@]}

declare -A NAMED_ARGS=()
declare -a MISC_ARGS=()

KEY=""
for i in $(seq 0 $((SRC_ARRAY_COUNT - 1)) )
do
  ARG="${SRC_ARRAY[$i]}"
  if [[ "${ARG}" =~ ^--.* ]]
  then
    NAMED_ARGS[${ARG}]="TRUE"
    KEY="${ARG}"
  elif [[ "${KEY}" != "" ]]
  then
    NAMED_ARGS[$KEY]="${ARG}"
    KEY=""
  else
    MISC_ARGS+=("${ARG}")
  fi
done

for key in "${!NAMED_ARGS[@]}"
do 
  echo "$key: ${NAMED_ARGS[$key]}"
done

for key in "${!MISC_ARGS[@]}"
do 
  echo "$key: ${MISC_ARGS[$key]}"
done
