#!/bin/bash

# Exit on failure
set -e

# ARGS

MEMORY=${1}
CORES=${2}
DISK_SIZE=${3}
DISK_FILE=${4}
NAME=${5}
TAGS=${6}

# CONSTANTS

ID=$(pvesh get /cluster/nextid)
HOSTNAME="vm${ID}"
STORAGE_NAME="local"

# VALIDATE

if [[ "${ID}" = "" ||  "${ID}" -lt "100" || "${ID}" -gt "253" ]];
then
    echo "❗  Invalid ID: ${ID}" >&2
    exit 1
fi

if [[ "${MEMORY}" = "" || "${MEMORY}" -lt "1" || "${MEMORY}" -gt "32" ]];
then
    echo "❗  Invalid MEMORY: ${MEMORY}" >&2
    exit 1
else
    MEMORY=$((${MEMORY} * 1024))
fi

if [[ "${CORES}" = "" || "${CORES}" -lt "1" || "${CORES}" -gt "4" ]];
then
    echo "❗  Invalid CORES: ${CORES}" >&2
    exit 1
fi

if [[ "${DISK_SIZE}" = "" ||  "${DISK_SIZE}" -lt "20" || "${DISK_SIZE}" -gt "4000" ]];
then
    echo "❗  Invalid DISK_SIZE: ${DISK_SIZE}" >&2
    exit 1
else
    DISK_SIZE="${DISK_SIZE}G"
fi

if [[ "${DISK_FILE}" = "" || ! -f "${DISK_FILE}" ]];
then
    echo "❗  Invalid DISK_FILE: ${DISK_FILE}" >&2
    exit 1
fi

if [[ "${NAME}" = "" ]];
then
    NAME="${HOSTNAME}"
fi

if [[ "${TAGS}" = "" ]];
then
    TAGS="unknown"
fi

# START

echo "🆕  Create a virtual machine"
qm create ${ID} --name ${NAME} --tags ${TAGS}
qm set ${ID} --memory ${MEMORY}
qm set ${ID} --sockets 1 --cores ${CORES}
qm set ${ID} --net0 virtio,bridge=vmbr0
qm set ${ID} --agent enabled=1

echo "➡️  Import the disk into the proxmox storage"
qm disk import ${ID} ${DISK_FILE} ${STORAGE_NAME} --format qcow2

echo "➡️  Add the imported disk to the VM"
qm set ${ID} \
    --scsihw virtio-scsi-pci \
    --scsi0 ${STORAGE_NAME}:${ID}/vm-${ID}-disk-0.qcow2

echo "➡️  Specify the boot disk"
qm set ${ID} --boot c --bootdisk scsi0

echo "➡️  Add support for VNC and a serial console"
qm set ${ID} --serial0 socket --vga serial0

echo "➡️  Add a CD-ROM for cloud-init"
qm set ${ID} --ide2 ${STORAGE_NAME}:cloudinit

echo "➡️  Set cloud-init"
qm set ${ID} --cicustom \
    "network=local:snippets/${ID}-network-config.yml,user=local:snippets/${ID}-user-config.yml"

echo "➡️  Write user config"
/srv/lib/write-user-config "/var/lib/vz/snippets/${ID}-user-config.yml" ${HOSTNAME} 

echo "➡️  Write network config"
/srv/lib/write-network-config "/var/lib/vz/snippets/${ID}-network-config.yml" ${ID}

# Wait for the maxdisk value to be set
# If it takes more than 10 attempts then exit
for i in $(seq "1" "10")
do
  CURRENT_DISK_SIZE=$(/srv/lib/get-vm-status "${ID}" | jq '.maxdisk')
  if [[ "${i}" -ge "10" ]]
  then
    echo "❗  Unable to resize disk. Exceeded max attempts: ${i}" >&2
    exit 1
  elif [[ "${CURRENT_DISK_SIZE}" -lt "2361393152" ]]
  then
    echo "⌛  Waiting for boot disk. Attempt: ${i}"
    sleep 0.2s
  else
    echo "🆗  Boot disk import complete"
    break
  fi
done

echo "➡️  Resize boot disk"
qm disk resize ${ID} scsi0 ${DISK_SIZE}

echo "✅  Created VM ${ID}"
