#!/bin/bash
set -euo pipefail


declare -A animals=(
  ["moo"]="cow"
  ["woof"]="dog"
)

# Then use them just like normal arrays. Use

#     animals['key']='value' to set value

#     "${animals[@]}" to expand the values

#     "${!animals[@]}" (notice the !) to expand the keys

# Don't forget to quote them:

echo "Animals with key moo:"
echo "${animals[moo]}"

echo "Animals values"
echo "${animals[@]}"

echo "Animals keys"
echo "${!animals[@]}"

echo "Start loop"

for sound in "${!animals[@]}"
do 
  echo "Animals with key ${sound}:"
  echo "$sound - ${animals[$sound]}"
done


echo "End loop"
