#!/bin/bash

# Exit on failure
set -e

CONFIG_FILE="${1}"
HOSTNAME="${2}"

# CONSTANTS

CONFIG_SRC="/srv/src/user-config-template.yml"
BOOTCMD_FILE="/srv/src/bootcmd"
RUNCMD_FILE="/srv/src/runcmd"

USER="stivisto"
SUDO_USER="radiko"
SSH_PORT="4444"

# VALIDATE

if [[ "${HOSTNAME}" = "" ]];
then
    echo "ERROR: Invalid HOSTNAME: ${HOSTNAME}"
    exit 1
fi

# OUTPUT

echo "CONFIG_SRC: ${CONFIG_SRC}"
echo "CONFIG_FILE: ${CONFIG_FILE}"

echo "HOSTNAME: ${HOSTNAME}"
echo "USER: ${USER}"
echo "SUDO_USER: ${SUDO_USER}"
echo "SSH_PORT: ${SSH_PORT}"

# START

echo "##### Set network config variables"
cp ${CONFIG_SRC}  ${CONFIG_FILE}
sed -i 's/${HOSTNAME}/'${HOSTNAME}'/' ${CONFIG_FILE}
sed -i 's/${USER}/'${USER}'/' ${CONFIG_FILE}
sed -i 's/${SUDO_USER}/'${SUDO_USER}'/' ${CONFIG_FILE}
"/srv/lib/replace-ssh-authorized-keys" ${CONFIG_FILE} "/root/.ssh/id_rsa.pub"
sed -i 's/${SSH_PORT}/'${SSH_PORT}'/' ${CONFIG_FILE}
"/srv/lib/replace-cmd" ${CONFIG_FILE} "${BOOTCMD_FILE}" "\${BOOTCMD_CONTENT}"
"/srv/lib/replace-cmd" ${CONFIG_FILE} "${RUNCMD_FILE}" "\${RUNCMD_CONTENT}"
