#!/bin/bash

# Exit on failure
set -e

VM_ID="${1}"
CONFIG_FILE="${2}"

# CONSTANTS

DIR="/root/infrastructure"
CONFIG_SRC="${DIR}/src/network-config-template.yml"

VM_IP="10.10.10.${VM_ID}"
GATEWAY_IP="10.10.10.1"

# VALIDATE

if [[ "${VM_ID}" = "" || "${VM_ID}" -lt "100" || "${VM_ID}" -gt "253" ]];
then
    echo "ERROR: Invalid VM_ID: ${VM_ID}"
    exit 1
fi

# OUTPUT

echo "DIR: ${DIR}"
echo "CONFIG_SRC: ${CONFIG_SRC}"
echo "CONFIG_FILE: ${CONFIG_FILE}"

echo "VM_ID: ${VM_ID}"
echo "VM_IP: ${VM_IP}"
echo "GATEWAY_IP: ${GATEWAY_IP}"

# START

echo "##### Set network config variables"
cp ${CONFIG_SRC}  ${CONFIG_FILE}
sed -i 's/${VM_IP}/'${VM_IP}'/' ${CONFIG_FILE}
sed -i 's/${GATEWAY_IP}/'${GATEWAY_IP}'/' ${CONFIG_FILE}
