#!/bin/bash

# Exit on failure
set -e

CONFIG_FILE="${1}"
VM_ID="${2}"

# CONSTANTS

CONFIG_SRC="/srv/src/network-config-template.yml"

VM_IP="10.10.10.${VM_ID}"
GATEWAY_IP="10.10.10.1"

# VALIDATE

if [[ "${VM_ID}" == "" || "${VM_ID}" -lt "100" || "${VM_ID}" -gt "253" ]];
then
    echo "❗  Invalid VM_ID: ${VM_ID}" >&2
    exit 1
fi

# START

cp ${CONFIG_SRC}  ${CONFIG_FILE}
sed -i 's/${VM_IP}/'${VM_IP}'/' ${CONFIG_FILE}
sed -i 's/${GATEWAY_IP}/'${GATEWAY_IP}'/' ${CONFIG_FILE}
