#!/bin/bash

# Exit on failure
set -e

VM_ID="${1}"
CONFIG_FILE="${2}"

# CONSTANTS

DIR="/root/infrastructure"
CONFIG_SRC="${DIR}/src/user-config-template.yml"
BOOTCMD_FILE="${DIR}/src/bootcmd"
RUNCMD_FILE="${DIR}/src/runcmd"

SSH_PORT="4444"
USER="stivisto"
SUDO_USER="radiko"

# VALIDATE

if [[ "${VM_ID}" = "" || "${VM_ID}" -lt "100" || "${VM_ID}" -gt "253" ]];
then
    echo "ERROR: Invalid VM_ID: ${VM_ID}"
    exit 1
fi

# OUTPUT

echo "DIR: ${DIR}"
echo "CONFIG_SRC: ${CONFIG_SRC}"
echo "CONFIG_FILE: ${CONFIG_FILE}"

echo "SSH_PORT: ${SSH_PORT}"
echo "USER: ${USER}"
echo "SUDO_USER: ${SUDO_USER}"

# START

echo "##### Set network config variables"
cp ${CONFIG_SRC}  ${CONFIG_FILE}
sed -i 's/${SSH_PORT}/'${SSH_PORT}'/' ${CONFIG_FILE}
sed -i 's/${USER}/'${USER}'/' ${CONFIG_FILE}
sed -i 's/${SUDO_USER}/'${SUDO_USER}'/' ${CONFIG_FILE}
"${DIR}/lib/replace-ssh-authorized-keys" ${CONFIG_FILE} "/root/.ssh/id_rsa.pub"
"${DIR}/lib/replace-cmd" ${CONFIG_FILE} "${BOOTCMD_FILE}" "\${BOOTCMD_CONTENT}"
"${DIR}/lib/replace-cmd" ${CONFIG_FILE} "${RUNCMD_FILE}" "\${RUNCMD_CONTENT}"
