#!/bin/bash

# Exit on failure
set -e

CONFIG_FILE="${1}"
HOSTNAME="${2}"

# CONSTANTS

CONFIG_SRC="/srv/src/user-config-template.yml"
HELLO_WORLD_FILE="/srv/src/50-hello-world"

USER="stivisto"
SUDO_USER="radiko"
SSH_PORT="4444"

# VALIDATE

if [[ "${HOSTNAME}" = "" ]];
then
    echo "ERROR: Invalid HOSTNAME: ${HOSTNAME}"
    exit 1
fi

# START

cp ${CONFIG_SRC}  ${CONFIG_FILE}
sed -i 's/${HOSTNAME}/'${HOSTNAME}'/' ${CONFIG_FILE}
sed -i 's/${USER}/'${USER}'/' ${CONFIG_FILE}
sed -i 's/${SUDO_USER}/'${SUDO_USER}'/' ${CONFIG_FILE}
"/srv/lib/yaml-embed-array" ${CONFIG_FILE} "/root/.ssh/id_rsa.pub"
sed -i 's/${SSH_PORT}/'${SSH_PORT}'/' ${CONFIG_FILE}
"/srv/lib/yaml-embed-block" ${CONFIG_FILE} "${HELLO_WORLD_FILE}" "\${HELLO_WORLD_CONTENT}"
