#!/bin/bash

# Exit on failure
set -e

# ARGS
SOURCE_FILE=${1}
INSERT_FROM_FILE=${2}
FIND=${3}
INDENT_COUNT=${4}

# CONSTANTS
TEMP_FILE=$(mktemp)

# VALIDATE

if [ "${SOURCE_FILE}" = "" ]; then
  echo "ERROR: Invalid SOURCE_FILE: ${SOURCE_FILE}" >&2
  exit 1
fi

if [ "${INDENT_COUNT}" = "" ]; then
  echo "ERROR: Invalid INDENT: ${INDENT_COUNT}" >&2
  exit 1
fi

# START
INDENT=""
for i in $(seq 1 ${INDENT_COUNT});
do
	INDENT="${INDENT}  "
done

INSERT=""
while read line;
do
  INSERT="$INSERT"$'\n'"${INDENT}- $line"
done < "${INSERT_FROM_FILE}"

# echo "$INSERT"

# Loop through each line of the source file and replace occurances
while IFS= read -r line;
do
  if [[ $line == *"$FIND"* ]];
  then
    echo "${line/$FIND/$INSERT}" >> ${TEMP_FILE}
  else
    echo "${line}" >> ${TEMP_FILE}
  fi
done < "${SOURCE_FILE}"

cp ${TEMP_FILE} ${SOURCE_FILE}
rm ${TEMP_FILE}
