#!/bin/bash

# Exit on failure
set -e

# ARGS
SOURCE_FILE=${1}
INSERT_FROM_FILE=${2}
FIND=${3}

# CONSTANTS
TEMP_FILE=$(mktemp)

# VALIDATE

if [[ ! -f "${SOURCE_FILE}" ]]; then
  echo "❗  Invalid SOURCE_FILE: ${SOURCE_FILE}" >&2
  exit 1
fi

if [[ ! -f "${INSERT_FROM_FILE}" ]]; then
  echo "❗  Invalid INSERT_FROM_FILE: ${INSERT_FROM_FILE}" >&2
  exit 1
fi

if [[ "${FIND}" == "" ]]; then
  echo "❗  Invalid FIND: ${FIND}" >&2
  exit 1
fi

# START

INSERT="|"

while read -r line;
do
  INSERT="$INSERT"$'\n'"      $line"
done < "${INSERT_FROM_FILE}"

# echo "$INSERT"

# Loop through each line of the source file and replace occurances
while IFS= read -r line;
do
  if [[ $line == *"$FIND"* ]];
  then
    echo "${line/$FIND/$INSERT}" >> "${TEMP_FILE}"
  else
    echo "${line}" >> "${TEMP_FILE}"
  fi
done < "${SOURCE_FILE}"

cp "${TEMP_FILE}" "${SOURCE_FILE}"
rm "${TEMP_FILE}"
