#cloud-config

# apt:
#   preserve_sources_list: true

# package_update: true
# package_upgrade: true
# package_reboot_if_required: true

# packages:
#   - uidmap

hostname: ${HOSTNAME}

users:
  - name: ${SUDO_USER}
    groups: sudo
    shell: /bin/bash
    # TODO: Remove password
    lock_passwd: false
    plain_text_passwd: pw
    sudo: true
    ssh_authorized_keys: ${SSH_AUTHORIZED_KEYS}
  - name: ${USER}
    shell: /bin/bash
    # TODO: Remove password
    lock_passwd: false
    plain_text_passwd: pw
    ssh_authorized_keys: ${SSH_AUTHORIZED_KEYS}

write_files:
  - path: /etc/ssh/sshd_config
    append: true
    content: |
      PermitRootLogin no
      PasswordAuthentication no
      Port ${SSH_PORT}
  - path: /root/bootcmd
    permissions: "0500"
    content: ${BOOTCMD_CONTENT}
  - path: /root/runcmd
    permissions: "0500"
    content: ${RUNCMD_CONTENT}

runcmd:
  - /root/runcmd

bootcmd:
  - /root/bootcmd

# power_state:
#   mode: reboot
#   message: "Time for a fresh start"
