#!/bin/bash
set -uo pipefail

LOG_FILE="/var/log/orbit.log"

log () {
  date --rfc-3339 ns | tr '\n' ' ' | sudo tee -a "${LOG_FILE}"
  echo "$1" | sudo tee -a "${LOG_FILE}"
}

echo-success () {
  echo -e "\e[32m ✔  $1\e[0m" >&2
}

echo-information () {
  echo -e "\e[34m ⓘ  $1\e[0m" >&2
}

echo-error () {
  echo -e "\e[31m !  $1\e[0m" >&2
}

echo-warning () {
  echo -e "\e[33m ⚠  $1\e[0m" >&2
}

echo-subsidiary () {
  echo -e "\e[37m    $1\e[0m" >&2
}

echo-step () {
  echo -e "\e[0m »  $1\e[0m" >&2
}

echo-break () {
  echo ""
}
