#cloud-config

hostname: ${HOSTNAME}

apt:
  preserve_sources_list: true
package_update: true
package_upgrade: true
package_reboot_if_required: true

users:
  - name: ${SUDO_USER}
    groups: sudo
    shell: /bin/bash
    # TODO: Remove password
    lock_passwd: false
    plain_text_passwd: pw
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys: ${SSH_AUTHORIZED_KEYS}
  - name: ${USER}
    shell: /bin/bash
    # TODO: Remove password
    lock_passwd: false
    plain_text_passwd: pw
    ssh_authorized_keys: ${SSH_AUTHORIZED_KEYS}

wireguard:
  interfaces:

write_files:

  - path: /etc/ssh/sshd_config
    append: true
    content: |
      PermitRootLogin no
      PasswordAuthentication no
      Port 22

bootcmd: []

runcmd: []
